--- !ruby/object:RDoc::RI::ModuleDescription 
attributes: []

class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: datadir
- !ruby/object:RDoc::RI::MethodSummary 
  name: inspect
comment: 
constants: []

full_name: Config
includes: []

instance_methods: []

name: Config
