--- !ruby/object:RDoc::RI::MethodDescription 
aliases: 
- !ruby/object:RDoc::RI::AliasName 
  name: "**"
block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Provides the cartesian product of two or more arrays.
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "  a = []\n  [1,2].product([4,5])\n  a  #=&gt; [[1, 4],[1, 5],[2, 4],[2, 5]]\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "CREDIT: Thomas Hafner"
full_name: Array#product
is_singleton: false
name: product
params: (*enums)
visibility: public
