---
stats:
  service: BasicStats

test:
  service : TestUnitSolo

rdoc_core:
  service : RDoc
  template: ./.config/rdoc-template
  output  : doc/rdoc/core
  title   : Facets Core API
  main    : doc/README.core
  options : "-S -a"
  include : [doc/README.core, README, lib/core/facets]

rdoc_lore:
  service : RDoc
  template: ./.config/rdoc-template
  output  : doc/rdoc/lore
  title   : Facets Lore API
  main    : doc/README.lore
  options : "-S -a"
  include : [doc/README.lore, README, lib/lore/facets]

rdoc_more:
  service : RDoc
  template: ./.config/rdoc-template
  output  : doc/rdoc/more
  title   : Facets More API
  main    : doc/README.more
  options : "-S -a"
  include : [doc/README.more, README, lib/more/facets]

# divide this up into three as well?
ridoc:
  service : RiDoc
  output  : doc/ri
  include : [lib/core/facets, lib/lore/facets, lib/more/facets]

#news: {}
#

vclog:
  service : VClog

gem:
  service : Gem
  include : [demo, doc, lib, task, test, "[A-Z]*"]
  exclude : [doc/ri]

rubyforge:
  service : Rubyforge
  groupid : 804

